### ISSUE TITLE
TempAR for Vita

### ISSUE THREAD

**Issue by Yohoki** [raing3/TempAR#1]
@raing3 I was just going to ask if it was alright if I uploaded a version of this made for the PS Vita, or if there's any way to get you to add my changes to your current version?

I didn't change much. I only added a new Mode, "Sony Vita" and made the form fill in the base address. It also automatically turns on the "Real Addresses" option, since that's useful in Vita. And I temporarily replace the Code Generator for AR with a code generator for VitaCheat.

I've just noticed you had the source code made available... so I may be able to make a branch, but I don't actually know how to use github that well and I didn't use the source code when making this... it was decompiled in Virtual Studio.

![Untitled](https://user-images.githubusercontent.com/44595371/57070838-3e750600-6c9e-11e9-85a2-7b2139d4ede5.png)

Until I get your permission, as well, I've not released it publicly.

**Comment by Yohoki** [comment]
Also, I just realised this is for the TempAR PSP plugin.... My code is for the TempAR Pointer Scanner... My bad.

**Comment by raing3** [comment]
Feel free to release your changes. I came across a thread a while back where people were using the pointer searcher and manually doing the format conversions which seems like a pain, don't want to stand in the way of making things easier for others. :)

I tried looking for the original source code to publish myself a few months back but couldn't find it, eventually I'll probably go digging further but I've been a bit too lazy.

**Comment by Yohoki** [comment]
If you use Visual studio and dotPeek, it decompiled it all just fine. It only took a few minor changes to get it working. The only thing that isn't working is the designer view, where you can see what the form looks like before having to build and debug... and by minor changes, I have no prior coding experience.... XD

Thanks very much! I'm sure the Vita scene will be very pleased to hear that. We've been using your program for a while, because it was the best thing available. But converting the codes is a big pain and hard to explain to noobies. I'll make sure to include a link back to your website for you.

**Comment by Yohoki** [comment]
I gotta credit you. Wouldn't feel right just changing a few dozen lines of code and saying it's all mine. Where can people get in touch with you to show some love or check out what you're doing?
