### ISSUE TITLE
Feature request: Add DB dumping function.

### ISSUE THREAD

**Issue by pthfdr-42** [raing3/TempAR#3]
I found that most databases on the Internet are corrupted for some reason.
Examples: [1](https://user-images.githubusercontent.com/42509223/58105946-e3d62680-7c19-11e9-8a6a-24c200811aa6.png), [2](https://user-images.githubusercontent.com/42509223/58105968-ec2e6180-7c19-11e9-98d6-5bae792d5702.png), [3](https://user-images.githubusercontent.com/42509223/58105969-ec2e6180-7c19-11e9-80be-f84bfb35270b.png).
Also, different formattings (`.BIN` and `.DB` formats) are also a problem. There are also some Japanese DBs that are encoded in ShiftJIS (which is a problem).
So I suggest that you should add a function to copy all valid codes to a separate file, in `.DB` (plaintext) format and with UTF-8 encoding.
In this way the files are easier to modify.

**Comment by gingerbeardman** [comment]
TempAR app is all but abandoned. 

So you might have more luck using one of the many code file editors to do what you want. 

You can also work on ShiftJIS with a good text editor.
